src/Entity/Ticket.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;
use App\Validator\BirthDayConstraint;


/**
 * @ORM\Entity(repositoryClass="App\Repository\TicketRepository")
 */
class Ticket
{

    const REDUCED_PRICE = true;
    const NO_REDUCED_PRICE = false;

    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @Assert\NotBlank
     * @Assert\Type("string")
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @Assert\NotBlank
     * @Assert\Type("string")
     * @ORM\Column(type="string", length=255)
     */
    private $firstname;

    /**
     * @Assert\NotBlank
     * @Assert\LessThan("today")
     * @ORM\Column(type="datetime")
     * @BirthDayConstraint()
     */
    private $birthday;

    /**
     * @Assert\NotBlank
     * @Assert\Type("string")
     * @Assert\Country
     * @ORM\Column(type="string", length=255)
     */
    private $nationality;

    /**
     * @Assert\NotBlank
     * @Assert\Type(type="bool")
     * @ORM\Column(type="boolean")
     */
    private $Reduced;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Booking", inversedBy="tickets")
     * @ORM\JoinColumn(nullable=false)
     */
    private $booking;

    /**
     * @Assert\NotNull
     * @ORM\Column(type="integer")
     */
    private $price;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getFirstname(): ?string
    {
        return $this->firstname;
    }

    public function setFirstname(string $firstname): self
    {
        $this->firstname = $firstname;

        return $this;
    }

    public function getBirthday(): ?\DateTimeInterface
    {
        return $this->birthday;
    }

    public function setBirthday(\DateTimeInterface $birthday): self
    {
        $this->birthday = $birthday;

        return $this;
    }

    public function getNationality(): ?string
    {
        return $this->nationality;
    }

    public function setNationality(string $nationality): self
    {
        $this->nationality = $nationality;

        return $this;
    }

    public function getReduced(): ?bool
    {
        return $this->Reduced;
    }

    public function setReduced(bool $Reduced): self
    {
        $this->Reduced = $Reduced;

        return $this;
    }


    public function getPrice(): ?int
    {
        return $this->price;
    }

    public function setPrice(int $price): self
    {
        $this->price = $price;

        return $this;
    }

    public function getBooking(): ?Booking
    {
        return $this->booking;
    }

    public function setBooking(?Booking $booking): self
    {
        $this->booking = $booking;

        return $this;
    }
}

src/Controller/CounterController.php
<?php

namespace App\Controller;

use App\Entity\Booking;
use App\Entity\Ticket;
use App\Form\BookingType;
use App\Form\TicketsType;
use App\Manager\TicketManager;
use App\Services\CodeNumberGenerator;
use App\Services\PriceCalculator;
use App\Services\StripeHandler;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\RequestStack;
use Symfony\Component\HttpFoundation\Response ;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Form\Extension\Core\Type\HiddenType;

class CounterController extends AbstractController
{

    /**
     * @var EntityManagerInterface
     */
    private $em;
    /**
     * @var Request
     */
    private $request;

    /**
     * @var TicketManager
     */
    private $ticketManager;

    public function __construct(TicketManager $ticketManager,RequestStack $requestStack, EntityManagerInterface $em)
    {
        $this->ticketManager = $ticketManager;
        $this->em = $em;
        $this->request = $requestStack->getCurrentRequest();
    }

    /**
     * @Route("/", name="booking")
     */
    public function bookingAction(Request $request, EntityManagerInterface $em)
    {
        $booking = $request->getSession()->get('booking', new Booking());
        $bookingForm = $this->createForm(BookingType::class, $booking);
        $bookingForm->handleRequest($request);


        if ($bookingForm->isSubmitted() && $bookingForm->isValid()) {

            $request->getSession()->set('booking', $booking);

            return $this->redirectToRoute('booking_tickets', ['booking' => $booking->getId()]);
        }

        return $this->render('counter/booking.html.twig', [
            'bookingForm' => $bookingForm->createView()
        ]);
    }

    /**
     * @Route("/tickets", name="booking_tickets")
     */
    public function bookingTicketsAction(Request $request, PriceCalculator $priceCalculator)
    {
        $booking = $request->getSession()->get('booking');


        if (!$booking) {
            return $this->redirectToRoute('booking');
        }

        $nbTicket = $booking->getNumberTicket();

        for ($i = $booking->getTickets()->count(); $i < $nbTicket; $i++) {
            $booking->addTicket(new Ticket());

        }

        $initNbTicket = $booking->getTickets()->count();

        for ($i = $nbTicket; $i < $initNbTicket; $i++) {
            $booking->removeTicket($booking->getTickets()->last());
        }

        $ticketsForm = $this->createForm(TicketsType::class, $booking);
        $ticketsForm->handleRequest($request);

        if ($ticketsForm->isSubmitted() && $ticketsForm->isValid()) {

            $priceCalculator->computePrice($booking);
            return $this->redirectToRoute('indent_order', ['booking' => $booking->getId()]);
        }


        return $this->render('counter/booking_tickets.html.twig', [
            'ticketsForm' => $ticketsForm->createView(),
            'reservation' => $booking

        ]);
    }

    /**
     * @Route("/order", name="indent_order")
     */
    public function indentAction(Request $request)
    {
        $booking = $request->getSession()->get('booking');

        return $this->render('counter/order.html.twig', [
            'reservation' => $booking

        ]);
    }

    /**
     * @Route("/payment", name="payment_order")
     */
    public function paymenttAction(Request $request, StripeHandler $stripeHandler, \Swift_Mailer $mailer): Response
    {
        /** @var Booking $booking */
        $booking = $request->getSession()->get('booking');

        $form = $this->createFormBuilder()
            ->add('stripeToken', HiddenType::class)
            ->getForm();
        $form->handleRequest($this->request);



        if ($form->isSubmitted() && $form->isValid()) {

            $code=rand(1000,100000);
            $booking->setCodeBooking($code);
            $email = $booking->getEmail();

            $message = (new \Swift_Message('Vos entrées pour le Musée du Louvre'))
                ->setFrom($email)
                ->setTo($email)
                ->setBody(
                    $this->renderView(
                        'counter/Emails/mailer.html.twig',
                        ['book'=>$booking]),
                         'text/html'
                         );
            $mailer->send($message);

 			$stripeHandler->charge($booking->getTotalAmount()*100, $form->getData()['stripeToken']);
            $this->em->persist($booking);
            $this->em->flush();
            return $this->redirectToRoute('order_done', ['id' => $booking->getId()]);
        }


        return $this->render('counter/payment.html.twig', [
            'payment' => $booking,
            'form' => $form->createView()

        ]);
    }

    /**
     * @Route("/done", name="order_done")
     */
    public function doneAction(Request $request)
    {
        $booking = $request->getSession()->get('booking');

        return $this->render('counter/order_done.html.twig',['payment' => $booking,]);
    }
}

templates/counter/booking.html.twig
{% extends 'base.html.twig' %}
{% form_theme bookingForm 'bootstrap_4_layout.html.twig' %}


{% block body %}

    <div class="card text-white bg-dark mb-3">
        <div class="card-header">Étape 1</div>
        <div class="card-body">
            <h5 class="card-title txtxs">Choix du/des billet(s)</h5>
        </div>
    </div>

    {{ form_start(bookingForm) }}



    <div class="row">
        <div class="col-12">
            <div class="card border-dark mb-3 ">
                <div class="card-header">Jour de visite</div>
                <div class="card-body">
                {{ form_widget(bookingForm.entry) }}
                 </div>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-12 col-sm-6">
            <div class="card border-dark mb-3">
                <div class="card-header">Type de réservation</div>
                <div class="card-body">
                    {{ form_widget(bookingForm.period) }}
                </div>
            </div>
        </div>

        <div class="col-12 col-sm-6">
            <div class="card border-dark mb-3">
                <div class="card-header">Nombre de réservation</div>
                <div class="card-body">
                    {{ form_widget(bookingForm.numberTicket) }}
                </div>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-12">
        <div class="card border-dark mb-3">
            <div class="card-header">Votre courriel</div>
            <div class="card-body">
                {{ form_widget(bookingForm.email.first) }}
                {{ form_errors(bookingForm.email.first) }}
                <br/>
                <p>Confirmez votre courriel</p>
                {{ form_widget(bookingForm.email.second) }}

            </div>
        </div>
        </div>
    </div>
    <div class="block">
        <button type="submit" class="btn btn-primary btn-lg btn-block btnxs">Etape suivante</button>
    </div>

    {{ form_end(bookingForm) }}

{% endblock %}

templates/counter/booking_tickets.html.twig
{% extends 'base.html.twig' %}
{% form_theme ticketsForm 'bootstrap_4_layout.html.twig' %}


{% block body %}

    <div class="card text-white bg-dark mb-3">
        <div class="card-header">Étape 2</div>
        <div class="card-body">
            <h5 class="card-title txtxs">Coordonnées</h5>
        </div>
    </div>

    <p class="block">
    <p><strong class="text-primary">Les billets sont nominatifs.</strong> Veuillez renseigner les informations demandées
        pour chaque bénéficiaire.<p/>

    <ul class="list-group ">
        <li class="list-group-item">Date de votre visite : {{ reservation.entry|date ('d/m/Y')}}</li>
        <li class="list-group-item">Type de billet :
            {% if reservation.period==true %}
                Vous visitez le Louvre toute la journée !
            {% else %}
                Nous vous souhaitons une bonne aprés-midi de curiosités !
            {% endif %}
        </li>
        <li class="list-group-item">Nombre de billet(s) : {{ reservation.numberTicket }}</li>
    </ul>
    </p>

    {{ form_start(ticketsForm) }}


    {% for ticketForm in ticketsForm.tickets %}


        <div class="card border-dark mb-3">
            <div class="card-header"><strong class="text-primary">Visiteur n° {{ loop.index }}</strong> </div>
            <div class="card-body">
                <div class="row">
                    <div class="col-12 col-lg-6">
                        <div class="card border-dark mb-3">
                            <div class="card-header">Nom</div>
                            <div class="card-body">
                                {{ form_widget(ticketForm.name) }}
                            </div>
                        </div>
                    </div>
                    <div class="col-12 col-lg-6">
                        <div class="card border-dark mb-3">
                            <div class="card-header">Prénom</div>
                            <div class="card-body">
                                {{ form_widget(ticketForm.firstname) }}
                            </div>
                        </div>
                    </div>
                </div>
                <br/>
                <div class="row">
                    <div class="col-12 col-lg-6">
                        <div class="card border-dark mb-3">
                            <div class="card-header">Date de naissance</div>
                            <div class="card-body">
                                {{ form_widget(ticketForm.birthday) }}
                            </div>
                        </div>
                    </div>
                    <div class="col-12 col-lg-6">
                        <div class="card border-dark mb-3">
                            <div class="card-header">Nationalité</div>
                            <div class="card-body">
                                {{ form_widget(ticketForm.nationality) }}
                            </div>
                        </div>
                    </div>
                </div>
                <div class="card-header">{{ form_label(ticketForm.reduced) }}<br/>{{ form_widget(ticketForm.reduced) }} </div>
            </div>
        </div>

    {% endfor %}

    <div class="row block">
        <div class="col-6"> <button type="button" class="btn btn-primary btn-lg btn-block btnxs"> <a class="btnForm" href="{{ path('booking') }}">Etape précédente</a></button></div>
        <div class="col-6"> <button type="submit" class="btn btn-primary btn-lg btn-block btnxs">Etape suivante</button></div>
    </div>
    {{ form_end(ticketsForm) }}


{% endblock %}

templates/counter/order.html.twig
{% extends 'base.html.twig' %}



{% block body %}

    <div class="card text-white bg-dark mb-3">
        <div class="card-header">Étape 3</div>
        <div class="card-body">
            <h5 class="card-title txtxs">Commande</h5>
        </div>
    </div>
    <p class="block">
    <p><strong class="text-primary">Votre commande</strong> est bientôt terminée, nous vous invitons à vérifier les
        informations ci-dessous avant règlement.<p/>

    <ul class="list-group ">
        <li class="list-group-item">Date de votre visite : {{ reservation.entry|date ('d/m/Y') }}</li>
        <li class="list-group-item">Type de billet :
            {% if reservation.period==true %}
                Vous visitez le Louvre toute la journée !
            {% else %}
                Nous vous souhaitons une bonne aprés-midi de curiosités !
            {% endif %}
        </li>
        <li class="list-group-item">Nombre de billet(s) : {{ reservation.numberTicket }}</li>
    </ul>
    </p>
    <wbr>
    <h4>Votre commande</h4>

    <div class="table-responsive" id="recap">
        <table class="table table-striped">
            <thead>
            <tr>
                <th scope="col">Nom</th>
                <th scope="col">Prénom</th>
                <th class="text-center" scope="col">Date de naissance</th>
                <th class="text-center" scope="col">Tarif</th>
                <th class="text-center" scope="col">Prix du billet</th>
            </tr>
            </thead>


            <tbody>

            {% for ticket in reservation.tickets %}

                <tr scope="row">
                    <td>{{ ticket.name|upper }}</td>
                    <td>{{ ticket.firstname }}</td>
                    <td class="text-center">{{ ticket.birthday|date ('d/m/Y') }}</td>
                    <td class="text-center">{{ ticket.reduced }}</td>
                    <td class="text-right">{{ ticket.price|number_format(2, ',', ' ') }} €</td>
                </tr>

            {% endfor %}
            </tbody>
        </table>

        <div class="row block card text-white bg-dark mb-3">

            <div class="js-price-amount card-body text-right" data-price ="{{ reservation.totalAmount * 100 }}">
                <h5 class="card-title">Montant Total : {{ reservation.totalAmount }} €</h5>
            </div>
        </div>


        <div class="row block">

            <div class="col-6">
                <button type="button" class="btn btn-primary btn-lg btn-block"><a class="btnForm"
                                                                                  href="{{ path('booking_tickets') }}">Etape
                        précédente</a></button>
            </div>

            <div class="col-6">
                <button id="customButton" type="submit" class="btn btn-primary btn-lg btn-block btnxs"><a class="btnForm" href="{{ path('payment_order') }}">Paiement</a></button>
            </div>
        </div>

    </div>
    <div id="stripe" data-stripe-public-key="{{ stripePublicKey }}"></div>



{% endblock %}

templates/counter/order_done.html.twig
{% extends 'base.html.twig' %}



{% block body %}

    <div class="card text-white bg-dark mb-3">
        <div class="card-header">Étape 5</div>
        <div class="card-body">
            <h5 class="card-title txtxs">Vos tickets sont dans votre boite Mail</h5>
        </div>
    </div>
    <div class="block">
        <p><strong class="text-primary">A bientôt au musée du Louvre,</strong> pour vous y rendre facilement, tous les accès sont indiqués ici .
        <p/>
    </div>
    <div class="block">
        <div class="row justify-content-end">
            <div class="col-12 col-sm-6">
                <div class="text-center block"><a class="logoLouvre"><img class="logoLouvre" src="{{ asset('img/logo-louvre.jpg') }}" alt="logo Louvre"/></a></div>
            </div>
            <div class="col-12 col-sm-6">
                <ul class="list-group">
                    <li class=" list-group-item card text-white bg-dark mb-3">Votre commande</li>
                    <li class="list-group-item">Date de votre visite : {{ payment.entry|date ('d/m/Y') }}</li>

                    <li class="list-group-item">Nombre de billet(s) : {{ payment.numberTicket }}</li>
                    <li class="list-group-item">Vos billets seront envoyés à :<br/>
                        <p class="pay card-title text-center">{{ payment.email }}</p>
                    </li>
                    <li class="list-group-item">
                        <div class="js-price-amount text-right" data-price="{{ payment.totalAmount * 100 }}">
                            <h5 class="card-title">Montant Total : <span class="pay">{{ payment.totalAmount }} €</span>
                            </h5>
                        </div>
                    </li>
                </ul>
            </div>
        </div>
    </div>
    <wbr>

    <div class="card text-white bg-dark mb-3">
        <div class="card-header">Paiement Réussi !
        </div>
        <div class="card-body">

                <button id="customButton" type="reset" class="btn btn-primary btn-lg btn-block btnxs"> <a class="btnForm" href="{{ path('booking') }}">Retour Guichet</a>
                </button>

        </div>
    </div>

{% endblock %}

templates/counter/payment.html.twig
{% extends 'base.html.twig' %}



{% block body %}

    <div class="card text-white bg-dark mb-3">
        <div class="card-header">Étape 4</div>
        <div class="card-body">
            <h5 class="card-title txtxs">Réglement</h5>
        </div>
    </div>
    <div class="block">
        <p><strong class="text-primary">Votre paiement</strong> validé, vous recevrez un courriel avec l’ensemble de vos
            tickets. N’oubliez pas de vérifier vos spam.
        <p/>
    </div>
    <div class="block">
        <div class="row justify-content-end">
            <div class="col-12 col-sm-6">
                <div class="text-center block"><a class="logoLouvre"><img class="logoLouvre" src="{{ asset('img/logo-louvre.jpg') }}"/></a></div>
            </div>
            <div class="col-12 col-sm-6">
                <ul class="list-group">
                    <li class=" list-group-item card text-white bg-dark mb-3">Votre commande</li>
                    <li class="list-group-item">Date de votre visite : {{ payment.entry|date ('d/m/Y') }}</li>
                    <li class="list-group-item">Nombre de billet(s) : {{ payment.numberTicket }}</li>
                    <li class="list-group-item">Vos billets seront envoyés à :<br/>
                        <p class="pay card-title text-center">{{ payment.email }}</p>
                    </li>
                    <li class="list-group-item">
                        <div class="js-price-amount text-right" data-price="{{ payment.totalAmount * 100 }}">
                            <h5 class="card-title">Montant Total : <span class="pay">{{ payment.totalAmount }} €</span>
                            </h5>
                        </div>
                    </li>
                </ul>
            </div>
        </div>
    </div>
    <wbr>
    <h4></h4>
    <div>
          <div class="container">
            <div class="card text-white bg-dark mb-3">
                <div class="row justify-content-center ">
                    <div class="col-10">
                        {{ form_start(form, {'attr': {'id': 'payment-form', 'data-key': stripePublicKey}}) }}
                        {{ form_widget(form) }}
                        <form action="/" method="post" id="payment-form">
                            <div class="form-row container">
                                <label for="card-element">
                                    Paiement par carte de crédit uniquement
                                </label>
                                <div id="card-element">
                                    <!-- A Stripe Element will be inserted here. -->
                                </div>

                                <!-- Used to display form errors. -->
                                <div id="card-errors" role="alert"></div>
                            </div>

                            <div class="form-row container">
                                <button id="customButton" type="submit" class="btn btn-primary btn-lg btn-block btnxs">payer
                                </button>
                            </div>
                        </form>
                        {{ form_end(form) }}
                        <br/>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}